apiVersion: v1
kind: Pod
metadata:
  name: test-single-module-biz1-version2
  labels:
    module-controller.koupleless.io/component: module # 必要，声明pod的类型，用于module controller管理
    module.koupleless.io/module0: 0.1.0
    module.koupleless.io/module1: 0.1.0
spec:
  containers:
    - name: biz1
      image: https://serverless-opensource.oss-cn-shanghai.aliyuncs.com/module-packages/stable/biz1-web-single-host-0.0.2-SNAPSHOT-ark-biz.jar
      env:
        - name: BIZ_VERSION
          value: 0.0.2-SNAPSHOT
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: base.koupleless.io/stack
                operator: In
                values:
                  - java # 多语言环境下可能有其他技术栈
              - key: base.koupleless.io/version
                operator: In
                values:
                  - 1.0.0  # 模块可能只能被调度到一些特殊版本的 node 上，如有这种限制，则必须有这个字段。
              - key: base.koupleless.io/name
                operator: In
                values:
                  - base  # 模块可能只能被调度到一些特殊版本的 node 上，如有这种限制，则必须有这个字段。
  tolerations:
    - key: "schedule.koupleless.io/virtual-node"
      operator: "Equal"
      value: "True"
      effect: "NoExecute"