version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - whitespace
  settings:
    cyclop:
      # The maximal code complexity to report.
      max-complexity: 18

formatters:
  enable:
    - gofumpt
    - goimports
